package com.supplybase.partners.partner;

public enum OnboardingStage {
    BASIC_DETAILS, WORK_CATEGORY, CITY, TERMS_PRIVACY, EARNING_POTENTIAL,
    WORKING_HOURS, PERMISSIONS, VERIFICATION, SCREENING, STARTER_KIT,
    PROFILE, TRAINING, ACTIVATION_REVIEW, COMPLETE
}
